baseURL = "https://sociedata.netlify.app/"
languageCode = "es-cl"
title = "Sociedata"
theme = "PaperMod"
defaultContentLanguage = "es"
disableKinds = ["taxonomy", "taxonomyTerm"]




[params]
  author = "Sociedata"
  description = "Datos sociales, visualizaciones públicas y análisis con sentido colectivo e intercultural."
  homeInfoParams = { Title = "Sociedata", Content = "Explora nuestros informes y visualizaciones con propósito social." }
  defaultTheme = "light"
  showShareButtons = true
  
[params.analytics]
  disable = true


[params.assets]
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Sobre"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Publicaciones"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 4

