baseURL = "https://sociedata.netlify.app/"
languageCode = "es-cl"
title = "Sociedata"
theme = "hello-friend-ng"
defaultContentLanguage = "es"

[pagination]
  pagerSize = 10

[params]
  author = "Sociedata"
  title = "Sociedata"
  subtitle = "Investigación social, visualización de datos y análisis público"
  homeSubtitle = "Datos para pensar el mundo"
  showReadingTime = true
  enableSharingButtons = false
  enableThemeToggle = false
  defaultTheme = "dark"


[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Publicaciones"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "apps"
    name = "Apps"
    url = "/apps/"
    weight = 3
